### ISSUE TITLE
(Solved) No such file error

### ISSUE THREAD

**Issue by Xalp** [luciusssss/VGaokao#1]
Have added the google drive content, but still cannot run. Lack of files.
Traceback (most recent call last):
  File "evidence_retrieval.py", line 19, in <module>
    from sentence_transformers import SentenceTransformer, util
ModuleNotFoundError: No module named 'sentence_transformers'
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 2229/2229 [00:00<00:00, 146954.58it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 557/557 [00:00<00:00, 152644.71it/s]
Traceback (most recent call last):
  File "train_hinge.py", line 27, in <module>
    from datasets import load_dataset, load_metric
ModuleNotFoundError: No module named 'datasets'
Traceback (most recent call last):
  File "inference.py", line 27, in <module>
    from datasets import load_dataset, load_metric
ModuleNotFoundError: No module named 'datasets'
Traceback (most recent call last):
  File "calculate_mc_acc.py", line 28, in <module>
    with open(nli_prob_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../models/vgaokao_soft-masking/test_prob_None.txt'

**Comment by luciusssss** [comment]
`../models/vgaokao_soft-masking/test_prob_None.txt` is the output file of `inference.py`. In your case, `inference.py` was not run successfully for lack of module `datasets` and `sentence-transformers`, so there is no output file from it.

It is my fault that I forgot to include the dependency of `sentence-transformers` and `datasets` in README.
I have updated the `README.md`. You can check the dependency description, install the needed dependency, and run the code again.
