### ISSUE TITLE
缺少文件的问题

### ISSUE THREAD

**Issue by gggor** [luciusssss/VGaokao#2]
../models/vgaokao_soft-masking/test_prob_None.txt
../models/vgaokao_soft-masking/config.json

您好，我在运行run.sh的时候提示缺少这两个文件，但是readme文档当中没有提到过/models/vgaokao_soft-masking这个文件夹，请问文章中有说到的soft-masking 和 hard-masking 是不是应该都有一个文件夹呢？ 如果有的话里面的文件应该去哪里下载呢？

**Comment by luciusssss** [comment]
`../models/vgaokao_soft-masking`文件夹是运行`run.sh`中的第一条命令（即`python3 train_hinge.py ...`）中建立的。
`../models/vgaokao_soft-masking/config.json`是`python3 train_hinge.py ...`的输出文件，`../models/vgaokao_soft-masking/test_prob_None.txt`是`python3 inference.py ...`的输出。

可以先尝试分别运行`run.sh`中的三条命令，看能否正常运行。正常运行成功的话不会缺少这些文件。

这份代码是soft masking的，hard masking因实现比较简单没有提供。

**Comment by gggor** [comment]
谢谢，问题已经解决了！
